# Generated by Django 5.2.1 on 2025-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=120)),
                ('Category', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('Date_Added', models.DateField()),
                ('Availability', models.CharField(max_length=120)),
            ],
        ),
    ]
