# Generated by Django 5.2.1 on 2025-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='Availability',
            field=models.CharField(max_length=50),
        ),
    ]
