# Generated by Django 5.2.1 on 2025-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_alter_book_details_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, to='lib.book_details'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
    ]
